export interface Article {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  date: string;
  time?: string;
  readTime: string;
  imageUrl: string;
  featured?: boolean;
}

export const categories = [
  "World",
  "Politics",
  "Business",
  "Technology",
  "Science",
  "Culture",
  "Opinion",
  "Sports",
];

export const breakingHeadline =
  "Global Climate Summit Reaches Historic Agreement on Carbon Emissions";

export const featuredArticle: Article = {
  id: "1",
  title: "The Architecture of Tomorrow: How Cities Are Redesigning Themselves for a Post-Carbon World",
  excerpt:
    "From Singapore to Copenhagen, a new generation of urban planners is reimagining what cities can be — transforming concrete jungles into living ecosystems.",
  category: "World",
  author: "Elena Vasquez",
  date: "April 1, 2026",
  time: "9:14 AM",
  readTime: "12 min",
  imageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&h=800&fit=crop",
  featured: true,
};

export const secondaryFeatured: Article[] = [
  {
    id: "f2",
    title: "Inside the G20's Emergency Session on AI Governance",
    excerpt: "World leaders convene for an unprecedented summit on regulating frontier AI systems.",
    category: "Politics",
    author: "Yuki Tanaka",
    date: "April 1, 2026",
    time: "8:30 AM",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=600&h=400&fit=crop",
  },
  {
    id: "f3",
    title: "The New Space Race Is Happening Right Now — and It's Private",
    excerpt: "Four companies are racing to put a permanent habitat in lunar orbit before 2027.",
    category: "Science",
    author: "Priya Sharma",
    date: "April 1, 2026",
    time: "7:55 AM",
    readTime: "10 min",
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=400&fit=crop",
  },
  {
    id: "f4",
    title: "Fed Holds Rates Steady, Signals Two Cuts Possible in 2026",
    excerpt: "The central bank held borrowing costs flat as it awaits clearer inflation data.",
    category: "Business",
    author: "Sarah Kim",
    date: "April 1, 2026",
    time: "11:20 AM",
    readTime: "4 min",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop",
  },
];

export const latestNews: Article[] = [
  {
    id: "l1",
    title: "Ukraine Peace Talks Resume in Vienna After Eight-Month Pause",
    excerpt: "",
    category: "World",
    author: "Ivan Petrov",
    date: "April 1, 2026",
    time: "11:42 AM",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "l2",
    title: "Fed Holds Rates Steady, Signals Two Cuts Possible in 2026",
    excerpt: "",
    category: "Business",
    author: "Sarah Kim",
    date: "April 1, 2026",
    time: "11:20 AM",
    readTime: "4 min",
    imageUrl: "",
  },
  {
    id: "l3",
    title: "OpenAI Announces GPT-5 With Reasoning Abilities 'Beyond Human Expert Level'",
    excerpt: "",
    category: "Technology",
    author: "Raj Mehta",
    date: "April 1, 2026",
    time: "10:58 AM",
    readTime: "6 min",
    imageUrl: "",
  },
  {
    id: "l4",
    title: "WHO Declares End to Mpox Global Health Emergency",
    excerpt: "",
    category: "Science",
    author: "Dr. Amara Singh",
    date: "April 1, 2026",
    time: "10:31 AM",
    readTime: "3 min",
    imageUrl: "",
  },
  {
    id: "l5",
    title: "Tesla's Robotaxi Network Expands to 12 Cities With Full Autonomy",
    excerpt: "",
    category: "Technology",
    author: "Lena Wolf",
    date: "April 1, 2026",
    time: "10:05 AM",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "l6",
    title: "India Surpasses China as World's Largest Economy by GDP — IMF",
    excerpt: "",
    category: "Business",
    author: "Arjun Nair",
    date: "April 1, 2026",
    time: "9:48 AM",
    readTime: "7 min",
    imageUrl: "",
  },
  {
    id: "l7",
    title: "Wildfires Rage Across Southern Europe, Thousands Evacuated",
    excerpt: "",
    category: "World",
    author: "Sofia Greco",
    date: "April 1, 2026",
    time: "9:22 AM",
    readTime: "4 min",
    imageUrl: "",
  },
  {
    id: "l8",
    title: "Brazil's Supreme Court Upholds Historic Amazon Protection Law",
    excerpt: "",
    category: "Politics",
    author: "Carlos Lima",
    date: "April 1, 2026",
    time: "8:50 AM",
    readTime: "5 min",
    imageUrl: "",
  },
];

export const editorsPicks: Article[] = [
  {
    id: "ep1",
    title: "The 15-Minute City Is Real — And People Actually Like It",
    excerpt: "An on-the-ground report from Paris three years after its transformation.",
    category: "Culture",
    author: "Margot Dupont",
    date: "April 1, 2026",
    time: "",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
  },
  {
    id: "ep2",
    title: "Why Your Brain Struggles With Exponential Growth",
    excerpt: "The cognitive science behind our persistent inability to grasp compound change.",
    category: "Science",
    author: "Dr. Leila Hassan",
    date: "March 31, 2026",
    time: "",
    readTime: "6 min",
    imageUrl: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&h=300&fit=crop",
  },
  {
    id: "ep3",
    title: "Africa's Sovereign Wealth Funds Are Reshaping Global Finance",
    excerpt: "A new generation of state-backed investors is changing who holds power on Wall Street.",
    category: "Business",
    author: "Kwame Asante",
    date: "March 31, 2026",
    time: "",
    readTime: "11 min",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop",
  },
  {
    id: "ep4",
    title: "The Quiet Return of Nuclear Power and What It Means",
    excerpt: "From South Korea to Poland, a new wave of reactors is reframing the energy debate.",
    category: "Technology",
    author: "Hans Brenner",
    date: "March 30, 2026",
    time: "",
    readTime: "9 min",
    imageUrl: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&h=300&fit=crop",
  },
];

export const gridArticles: Article[] = [
  {
    id: "5",
    title: "Inside the Battle for Control of the World's Rarest Minerals",
    excerpt: "As nations compete for lithium and cobalt, new alliances are reshaping geopolitics.",
    category: "Politics",
    author: "James Okoro",
    date: "March 31, 2026",
    time: "",
    readTime: "10 min",
    imageUrl: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop",
  },
  {
    id: "6",
    title: "AI-Generated Music Tops Charts for the First Time",
    excerpt: "A track produced entirely by AI forces a reckoning over creativity and copyright.",
    category: "Technology",
    author: "Nina Patel",
    date: "March 31, 2026",
    time: "",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=400&fit=crop",
  },
  {
    id: "7",
    title: "The Last Fishermen of the Aral Sea",
    excerpt: "A photographic essay documents those who stayed as one of the world's great lakes disappeared.",
    category: "Culture",
    author: "Dmitri Volkov",
    date: "March 30, 2026",
    time: "",
    readTime: "14 min",
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=400&fit=crop",
  },
  {
    id: "8",
    title: "New Study Links Ultra-Processed Foods to Cognitive Decline",
    excerpt: "Research across 12 countries reveals a striking correlation between diet and brain health.",
    category: "Science",
    author: "Dr. Amara Singh",
    date: "March 30, 2026",
    time: "",
    readTime: "6 min",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop",
  },
  {
    id: "g5",
    title: "Europe's Mega-Drought Is Testing the Limits of Agriculture",
    excerpt: "Farmers across Spain and Italy face unprecedented water restrictions as reservoirs hit record lows.",
    category: "World",
    author: "Ana Torres",
    date: "March 29, 2026",
    time: "",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=600&h=400&fit=crop",
  },
  {
    id: "g6",
    title: "The Collapse of Streaming: Why Audiences Are Going Back to Live TV",
    excerpt: "After a decade of on-demand dominance, live broadcast is staging an unexpected comeback.",
    category: "Culture",
    author: "Priya Sharma",
    date: "March 29, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&h=400&fit=crop",
  },
];

export const businessArticles: Article[] = [
  {
    id: "b1",
    title: "Central Banks Weigh Digital Currency Rollout Amid Uncertainty",
    excerpt: "Federal Reserve officials signal a cautious approach to a digital dollar as inflation persists.",
    category: "Business",
    author: "Marcus Chen",
    date: "April 1, 2026",
    time: "",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&h=400&fit=crop",
  },
  {
    id: "b2",
    title: "How Hedge Funds Are Betting Big on Water Scarcity",
    excerpt: "As aquifers run dry across three continents, investors see opportunity in crisis.",
    category: "Business",
    author: "Fiona Blake",
    date: "March 31, 2026",
    time: "",
    readTime: "9 min",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop",
  },
  {
    id: "b3",
    title: "The $4 Trillion Carbon Credit Market Is Finally Being Taken Seriously",
    excerpt: "After years of greenwashing scandals, reformed standards are bringing institutional investors back.",
    category: "Business",
    author: "Aiko Tanaka",
    date: "March 30, 2026",
    time: "",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop",
  },
  {
    id: "b4",
    title: "Japan's Yen Hits 40-Year Low as BOJ Holds Rates",
    excerpt: "Currency traders brace for intervention as the yen slides past 170 to the dollar.",
    category: "Business",
    author: "Kenji Nakamura",
    date: "March 29, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&h=400&fit=crop",
  },
  {
    id: "b5",
    title: "The Rise of Sovereign AI Funds: Why Governments Are Investing Directly in Chips",
    excerpt: "At least 14 countries now run state-backed semiconductor investment vehicles.",
    category: "Business",
    author: "Lisa Hartmann",
    date: "March 28, 2026",
    time: "",
    readTime: "6 min",
    imageUrl: "",
  },
  {
    id: "b6",
    title: "Global Shipping Rates Surge as Panama Canal Drought Worsens",
    excerpt: "Container costs have tripled since January as the bottleneck reshapes trade routes.",
    category: "Business",
    author: "Carlos Lima",
    date: "March 28, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "",
  },
];

export const techArticles: Article[] = [
  {
    id: "t1",
    title: "Breakthrough in Quantum Computing Promises a New Era of Drug Discovery",
    excerpt: "Researchers demonstrate a 1,000-qubit processor capable of simulating molecular interactions.",
    category: "Technology",
    author: "Dr. Sarah Okonkwo",
    date: "April 1, 2026",
    time: "",
    readTime: "6 min",
    imageUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop",
  },
  {
    id: "t2",
    title: "Inside Apple's Secretive Lab Building the Neural Interface of Tomorrow",
    excerpt: "Reports surface of a decade-long project to create a chip that interfaces with the human brain.",
    category: "Technology",
    author: "Lena Wolf",
    date: "March 31, 2026",
    time: "",
    readTime: "11 min",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop",
  },
  {
    id: "t3",
    title: "China's New Undersea Internet Cable Is Reshaping Global Data Flow",
    excerpt: "A Beijing-funded cable network now carries 30% of global internet traffic — largely unnoticed.",
    category: "Technology",
    author: "Wei Zhang",
    date: "March 30, 2026",
    time: "",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
  },
  {
    id: "t4",
    title: "EU Passes Sweeping AI Liability Law With Teeth",
    excerpt: "Companies that deploy AI causing harm will face strict liability under the new framework.",
    category: "Technology",
    author: "Anna Bergström",
    date: "March 29, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
  },
  {
    id: "t5",
    title: "Google DeepMind Cracks New Protein Structures Linked to Aging",
    excerpt: "The lab's latest model reveals structures that could unlock therapies for age-related disease.",
    category: "Science",
    author: "Dr. Amara Singh",
    date: "March 28, 2026",
    time: "",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&h=400&fit=crop",
  },
  {
    id: "t6",
    title: "The Open-Source AI Movement Is Winning — Here's Why It Matters",
    excerpt: "Meta, Mistral and a community of thousands are outpacing closed models on key benchmarks.",
    category: "Technology",
    author: "Raj Mehta",
    date: "March 27, 2026",
    time: "",
    readTime: "9 min",
    imageUrl: "",
  },
  {
    id: "t7",
    title: "Robotics Startups Raise Record $18B in Q1 as Factory Automation Booms",
    excerpt: "",
    category: "Technology",
    author: "Nina Patel",
    date: "March 27, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "",
  },
  {
    id: "t8",
    title: "Samsung Unveils First Consumer Solid-State Battery Phone",
    excerpt: "",
    category: "Technology",
    author: "Kenji Nakamura",
    date: "March 26, 2026",
    time: "",
    readTime: "3 min",
    imageUrl: "",
  },
  {
    id: "t9",
    title: "NASA Confirms Water Ice Deposits at Lunar South Pole",
    excerpt: "",
    category: "Science",
    author: "Priya Sharma",
    date: "March 26, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "t10",
    title: "Self-Driving Trucks Begin First Cross-Country Commercial Routes in the US",
    excerpt: "",
    category: "Technology",
    author: "James Park",
    date: "March 25, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "t11",
    title: "New Carbon Capture Technology Claims 90% Efficiency in Open Air",
    excerpt: "",
    category: "Science",
    author: "Dr. Amara Singh",
    date: "March 25, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "",
  },
  {
    id: "t12",
    title: "Deepfake Detection Tools Are Falling Further Behind AI-Generated Video",
    excerpt: "",
    category: "Technology",
    author: "Raj Mehta",
    date: "March 24, 2026",
    time: "",
    readTime: "6 min",
    imageUrl: "",
  },
  {
    id: "t13",
    title: "Biotech Startup Raises $2B to Mass-Produce Lab-Grown Organs",
    excerpt: "",
    category: "Science",
    author: "Dr. Sarah Okonkwo",
    date: "March 23, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "t14",
    title: "TSMC Breaks Ground on World's Largest Chip Fabrication Plant in Arizona",
    excerpt: "",
    category: "Technology",
    author: "Wei Zhang",
    date: "March 23, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "",
  },
];

export const opinionArticles: Article[] = [
  {
    id: "9",
    title: "We Cannot Afford to Ignore the Warning Signs in Southeast Asia",
    excerpt:
      "The geopolitical fault lines emerging in the Pacific demand immediate diplomatic attention from the West.",
    category: "Opinion",
    author: "Prof. Catherine Moore",
    date: "April 1, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "",
  },
  {
    id: "10",
    title: "The Case for Universal Basic Infrastructure Over Universal Basic Income",
    excerpt:
      "Instead of writing checks, governments should invest in the systems that make a dignified life possible.",
    category: "Opinion",
    author: "Ricardo Mendes",
    date: "March 31, 2026",
    time: "",
    readTime: "7 min",
    imageUrl: "",
  },
  {
    id: "11",
    title: "Why the Nobel Committee Got It Wrong This Year",
    excerpt:
      "The decision to award the Peace Prize to a sitting head of state undermines the institution's credibility.",
    category: "Opinion",
    author: "Fiona Blackwell",
    date: "March 30, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "",
  },
];

export const entertainmentArticles: Article[] = [
  {
    id: "ent1",
    title: "Cannes 2026: The Films Already Generating Awards Buzz",
    excerpt: "From a Brazilian epic to a surprise South Korean entry, this year's lineup is the most diverse in the festival's history.",
    category: "Culture",
    author: "Sophie Laurent",
    date: "April 1, 2026",
    time: "10:30 AM",
    readTime: "6 min",
    imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=500&fit=crop",
  },
  {
    id: "ent2",
    title: "Taylor Swift's Eras Tour Film Breaks Streaming Records",
    excerpt: "The concert documentary surpassed 200 million views in its first week on the platform.",
    category: "Culture",
    author: "Marcus Bell",
    date: "March 31, 2026",
    time: "3:15 PM",
    readTime: "3 min",
    imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=500&fit=crop",
  },
  {
    id: "ent3",
    title: "The Quiet Return of Classic TV: Why Audiences Are Turning Off Streaming",
    excerpt: "Nostalgia, simplicity, and fatigue with algorithmic recommendations are driving viewers back to scheduled programming.",
    category: "Culture",
    author: "Diana Osei",
    date: "March 30, 2026",
    time: "",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&h=500&fit=crop",
  },
  {
    id: "ent4",
    title: "Billie Eilish Announces World Tour with 50-City Carbon-Neutral Pledge",
    excerpt: "The artist will offset all touring emissions and partner with environmental groups at each venue.",
    category: "Culture",
    author: "Marcus Bell",
    date: "March 29, 2026",
    time: "",
    readTime: "4 min",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop",
  },
  {
    id: "ent5",
    title: "How Video Games Are Outpacing Hollywood in Storytelling",
    excerpt: "With budgets rivalling blockbuster films, the games industry is producing narratives that cinema struggles to match.",
    category: "Culture",
    author: "Kenji Nakamura",
    date: "March 28, 2026",
    time: "",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=500&fit=crop",
  },
  {
    id: "ent6",
    title: "The New Wave of South Asian Cinema Taking Over Global Screens",
    excerpt: "A generation of filmmakers from Mumbai to Lahore is redefining what international cinema looks like.",
    category: "Culture",
    author: "Priya Sharma",
    date: "March 27, 2026",
    time: "",
    readTime: "5 min",
    imageUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&h=500&fit=crop",
  },
];

export const trendingArticles = [
  { id: "tr1", title: "Mars Colony Reports First Successful Harvest", category: "Science" },
  { id: "tr2", title: "Stock Markets Rally After Trade Deal Announcement", category: "Business" },
  { id: "tr3", title: "Olympic Committee Announces Surprising 2036 Host City", category: "Sports" },
  { id: "tr4", title: "Renowned Director's Final Film Premieres to Standing Ovation", category: "Culture" },
  { id: "tr5", title: "Parliament Passes Landmark Data Privacy Legislation", category: "Politics" },
];
